task:
  name: "[system libs, no depends, fuzz, valgrind]  [jammy]"
  container:
    image: ubuntu:22.04
    cpu: 4
    memory: 16G
    greedy: true
  timeout_in: 120m
  env:
    FILE_ENV: "./ci/test/00_setup_env_native_fuzz_with_valgrind.sh"
    MAKEJOBS: "-j20"
    DANGER_RUN_CI_ON_HOST: "1"
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  upstream_clone_script:
    - cd /tmp
    - apt update && apt install git -y
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
    - mkdir -p /tmp/bitcoin-core/ci/scratch
    - mv /tmp/cirrus-ci-build /tmp/bitcoin-core/ci/scratch/qa-assets
  ci_script:
    - cd /tmp/bitcoin-core
    - ./ci/test_run_all.sh
task:
  name: "[depends, fuzz, msan]  [jammy]"
  container:
    image: ubuntu:22.04
    cpu: 4
    memory: 16G
    greedy: true
  timeout_in: 120m
  env:
    FILE_ENV: "./ci/test/00_setup_env_native_fuzz_with_msan.sh"
    MAKEJOBS: "-j10"
    DANGER_RUN_CI_ON_HOST: "1"
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  upstream_clone_script:
    - cd /tmp
    - apt update && apt install git -y
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
    - mkdir -p /tmp/bitcoin-core/ci/scratch
    - mv /tmp/cirrus-ci-build /tmp/bitcoin-core/ci/scratch/qa-assets
  ci_script:
    - cd /tmp/bitcoin-core
    - sed -i 's|FuzzedDataProvider fuzzed_data_provider|return;FuzzedDataProvider fuzzed_data_provider|g'  ./src/test/fuzz/strprintf.cpp  # Avoid tinyformat issue
    - ./ci/test_run_all.sh
task:
  name: "[system libs, no depends, fuzz, sanitizers]  [jammy]"
  container:
    image: ubuntu:22.04
    cpu: 4  # To catch potential timeouts early, this task must replicate the config from https://github.com/bitcoin/bitcoin/blob/master/.cirrus.yml
    memory: 16G
    greedy: true
  timeout_in: 120m
  env:
    FILE_ENV: "./ci/test/00_setup_env_native_fuzz.sh"
    MAKEJOBS: "-j10"
    DANGER_RUN_CI_ON_HOST: "1"
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  upstream_clone_script:
    - cd /tmp
    - apt update && apt install git -y
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
    - mkdir -p /tmp/bitcoin-core/ci/scratch
    - mv /tmp/cirrus-ci-build /tmp/bitcoin-core/ci/scratch/qa-assets
  ci_script:
    - cd /tmp/bitcoin-core
    - ./ci/test_run_all.sh
