task:
  name: "[system libs, no depends, fuzz, valgrind]  [focal]"
  container:
    image: ubuntu:20.04
    cpu: 2
    memory: 8G
  timeout_in: 300m
  # Need to use credits because the timeout was bumped
  use_compute_credits: $CIRRUS_REPO_FULL_NAME == 'bitcoin-core/qa-assets'
  env:
    FILE_ENV: "./ci/test/00_setup_env_native_fuzz_with_valgrind.sh"
    MAKEJOBS: "-j4"
    DANGER_RUN_CI_ON_HOST: "1"
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  upstream_clone_script:
    - cd /tmp
    - apt update && apt install git -y
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
    - mkdir -p /tmp/bitcoin-core/ci/scratch
    - mv /tmp/cirrus-ci-build /tmp/bitcoin-core/ci/scratch/qa-assets
  ci_script:
    - cd /tmp/bitcoin-core
    - ./ci/test_run_all.sh
task:
  name: "[depends, fuzz, msan]  [focal]"
  container:
    image: ubuntu:20.04
    cpu: 2
    memory: 8G
  timeout_in: 120m
  env:
    FILE_ENV: "./ci/test/00_setup_env_native_fuzz_with_msan.sh"
    MAKEJOBS: "-j4"
    DANGER_RUN_CI_ON_HOST: "1"
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  upstream_clone_script:
    - cd /tmp
    - apt update && apt install git -y
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
    - mkdir -p /tmp/bitcoin-core/ci/scratch
    - mv /tmp/cirrus-ci-build /tmp/bitcoin-core/ci/scratch/qa-assets
  ci_script:
    - cd /tmp/bitcoin-core
    - sed -i 's|FuzzedDataProvider fuzzed_data_provider|return;FuzzedDataProvider fuzzed_data_provider|g'  ./src/test/fuzz/strprintf.cpp  # Avoid tinyformat issue
    - ./ci/test_run_all.sh
task:
  name: "[system libs, no depends, fuzz, sanitizers]  [focal]"
  container:
    image: ubuntu:20.04
    cpu: 2  # To catch potential timeouts early, this task must replicate the config from https://github.com/bitcoin/bitcoin/blob/8e1913ae025/.cirrus.yml#L139
    memory: 8G
  timeout_in: 120m
  env:
    FILE_ENV: "./ci/test/00_setup_env_native_fuzz.sh"
    MAKEJOBS: "-j4"
    DANGER_RUN_CI_ON_HOST: "1"
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  upstream_clone_script:
    - cd /tmp
    - apt update && apt install git -y
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
    - mkdir -p /tmp/bitcoin-core/ci/scratch
    - mv /tmp/cirrus-ci-build /tmp/bitcoin-core/ci/scratch/qa-assets
  ci_script:
    - cd /tmp/bitcoin-core
    - ./ci/test_run_all.sh
