# Copyright (c) The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://opensource.org/license/mit.

name: CI
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-matrix:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'fuzz (dummy)'
            runner: 'ubuntu-latest'

    steps:
      - name: Checkout Bitcoin Core
        uses: actions/checkout@v5
        with:
          repository: bitcoin/bitcoin
          fetch-depth: 1
